### ISSUE TITLE
Speed issue

### ISSUE THREAD

**Issue by NirvikNU** [JuliaDiffEq/SciPyDiffEq.jl#4]
Is there any overhead or are these solvers inherently very slow compared to DifferentialEquations?

**Comment by ChrisRackauckas** [comment]
See the readme. Run the overhead measurement on your computer to double check. I found this wrapper to be 3x faster than using SciPy from Python with Numba (because of the function Jitting). See what you get!

**Comment by NirvikNU** [comment]
Okay. Got it!
Is it the same for MATLABDiffEq and deSolveDiffEq?
I just want to ensure that the benchmarking is comparable when run directly
from Julia or if they need to be run from their own languages.

**Comment by ChrisRackauckas** [comment]
See the READMEs in each. MATLABDiffEq is about 1-1, deSolveDiffEq introduces an overhead of around 3x.

**Comment by NirvikNU** [comment]
Got it...another issue is that I see that some solvers like the Sundials,
native Julia solvers come with their own interpolant. So can the
interpolant be considered an intrinsic part of the algorithm? I know for
example in MATLAB the deval function is used to interpolate from the
solution structure (although the MATHWORKS manual page on deval doesnt
mention what type of interpolation is used for each algorithm). How does
SciPyDiffEq, deSolveDiffEq and MATLABDiffEq deal with such interpolations?
Or does it do a linear interpolation for these algorithms? In that case
will comparison across languages/algorithms depend on the type of
interpolation used?

**Comment by ChrisRackauckas** [comment]
>some solvers like the Sundials, native Julia solvers come with their own interpolant

Sundials doesn't expose it post solution, so we utilize their internal one in the integrator but use a Hermite from the solve (since it allows saving `du` which is all that's needed for Hermite). Since it's 3rd order it works about as well as the Sundials internal one anyways though.

> I know for example in MATLAB the deval function is used to interpolate from the solution structure

We don't use that yet, though we could if you have a use for it. Given the speed of MATLAB though, I generally don't put much effort into giving that library all of the features.

>How does SciPyDiffEq, deSolveDiffEq and MATLABDiffEq deal with such interpolations?

deSolve doesn't have an interpolation, so it's just linear. SciPy exposes it, so it defaults to using the one returned from SciPy (i.e. it has full integration).

**Comment by NirvikNU** [comment]
Thanks for clarifying. I dont know what algorithm MATLAB uses for deval,
but I ran some benchmarks to compare the solutions directly from MATLAB and
via Julia and the results are pretty much the same. So I presume its
inconsequential.

**Comment by ChrisRackauckas** [comment]
Not much else here. Cheers!
